version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Svmr12!@
      MYSQL_DATABASE: pip
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  fund-transfer:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pip?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Svmr12!@
    ports:
      - "8080:8080"


